# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='extra_info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
